# Site settings
title: High Voltage
description: >
  High Voltage serves static pages in your Rails app
url: "http://thoughtbot.github.io/high_voltage/"
repository_url: "http://github.com/thoughtbot/high_voltage"
documentation_url: "http://github.com/thoughtbot/high_voltage/blob/master/README.md"
thoughtbot_url: "http://thoughtbot.com"
license_url: "https://github.com/thoughtbot/high_voltage/blob/master/MIT-LICENSE"

# Build settings
markdown: kramdown
sass:
  sass_dir: stylesheets

gems: [bourbon]

exclude:
  - log
  - pkg
  - Gemfile
  - Gemfile.lock
  - vendor
